// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Liem Tran",
            "email": "liemtran1414@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/broadcast-sheet": {
            "get": {
                "description": "Stream sheet changes using Server-Sent Events (SSE)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "sheets"
                ],
                "summary": "Broadcast sheet changes in real-time",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sheet ID to observe",
                        "name": "sheetID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Stream of sheet changes",
                        "schema": {
                            "$ref": "#/definitions/model.DocumentChange"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Missing or invalid sheetID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "408": {
                        "description": "Request Timeout - Client cancelled the request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/collections": {
            "get": {
                "description": "Returns the number of collections in the Firestore database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "Get Firestore collections count",
                "responses": {
                    "200": {
                        "description": "Collections count response",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the application is running and healthy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Everything is good",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "firestore.CollectionRef": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID is the collection identifier.",
                    "type": "string"
                },
                "parent": {
                    "description": "Parent is the document of which this collection is a part. It is\nnil for top-level collections.",
                    "$ref": "#/definitions/firestore.DocumentRef"
                },
                "path": {
                    "description": "The full resource path of the collection: \"projects/P/databases/D/documents...\"",
                    "type": "string"
                }
            }
        },
        "firestore.DocumentRef": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "The ID of the document: the last component of the resource path.",
                    "type": "string"
                },
                "parent": {
                    "description": "The CollectionRef that this document is a part of. Never nil.",
                    "$ref": "#/definitions/firestore.CollectionRef"
                },
                "path": {
                    "description": "The full resource path of the document. A document \"doc-1\" in collection\n\"coll-1\" would be: \"projects/P/databases/D/documents/coll-1/doc-1\".",
                    "type": "string"
                }
            }
        },
        "model.DocumentChange": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "sheet": {
                    "$ref": "#/definitions/model.Sheet"
                }
            }
        },
        "model.Menu": {
            "type": "object",
            "properties": {
                "menuItems": {
                    "description": "Embedded items, not references",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MenuItem"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.MenuItem": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "boolean"
                },
                "category": {
                    "type": "string"
                },
                "itemID": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "description": "float64 is more common for currency",
                    "type": "number"
                }
            }
        },
        "model.Sheet": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdBy": {
                    "description": "Reference to the user who created the sheet",
                    "$ref": "#/definitions/firestore.DocumentRef"
                },
                "endAt": {
                    "description": "End time for the sheet",
                    "type": "string"
                },
                "id": {
                    "description": "Firestore ID, not stored in Firestore",
                    "type": "string"
                },
                "menu": {
                    "description": "Changed to match original design",
                    "$ref": "#/definitions/model.Menu"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Drink and Eat vercel function API",
	Description:      "Drink and Eat API that hosted on vercel as microservice.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
